/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../miniunz/miniunz.h"

/* Header for class com_yyx_me_unzip_ZipNativeUtils */

#ifndef _Included_com_yyx_me_unzip_ZipNativeUtils
#define _Included_com_yyx_me_unzip_ZipNativeUtils
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_yyx_me_unzip_ZipNativeUtils
 * Method:    unzip
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yyx_1me_unzip_ZipNativeUtils_unzip
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_yyx_me_unzip_ZipNativeUtils
 * Method:    unzip1
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yyx_1me_unzip_ZipNativeUtils_unzip1
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
